### ISSUE TITLE
Suggestions about module functionality

### ISSUE THREAD

**Issue by Methyle** [ThePixelDeveloper/kohana-sitemap#1]
I think it will be great if module automatically save / update url data in sitemap.xml file and make it compressed copy.

**Comment by ThePixelDeveloper** [comment]
You can use Sam Clarks caching library to cache the output.

Ps, the file sitemap.xml does not actually exist. It's mapped to a controller/action.

**Comment by Methyle** [comment]
But, I think, without this functionality your module lose it's main idea. User must save url data, then get saved data, and only after that module format data to XML sitemap.

**Comment by ThePixelDeveloper** [comment]
I don't understand what you're asking for. If you can come back with a clear description of what you would like then post a reply otherwise it is closed.

Fork the code if you're desperate.

**Comment by Methyle** [comment]
I would like one time add, update or delete this data  in my application, and after that forget about it. After that module generate ready to use sitemap.xml file. Sorry for my English :)

**Comment by ThePixelDeveloper** [comment]
You can run Kohana from the terminal so you could try the following

php index.php --uri=controller/action > sitemap.xml

Where the controller would generate the XML output. We then pipe this to a new file, to update simply run that command on a cron.

As for deleting and updating specific values, forget it. You will have to fork the code and do it yourself.
