### ISSUE TITLE
Including XSL

### ISSUE THREAD

**Issue by akiva** [ThePixelDeveloper/kohana-sitemap#4]
It would be great if we could include an XSL file to enhance our sitemaps, should a human want to view it, a la http://www.zeldman.com/sitemap.xml

**Comment by ThePixelDeveloper** [comment]
I'm having trouble with this, does someone know how to apply an XSL?

https://github.com/ThePixelDeveloper/kohana-sitemap/commit/c8c4af8aa8e7334a16ad9898e430c16d26f6dcb6

**Comment by akiva** [comment]
You simply declare the link to the XSL stylesheet a la:

```
<?xml-stylesheet type="text/xsl" href="http://your.site.here/sitemap.xsl"?>
```

What you will need to do is check first to see if the user supplies a string to a valid/existing XSL file and that is all. The rest should be up to them, as actually creating the stylesheet should be beyond the scope of your plugin, IMO.

**Comment by akiva** [comment]
I think I just closed the ticket? Sorry, if so, please re-open. :S

**Comment by ThePixelDeveloper** [comment]
Hmm, let me re-open it.

The code I have uploaded only checks to see if any have been added and imports them. I assume the XSLTProcessor does its own validations. Since I have never used XSL I am unsure of it's usage. If you could perhaps test it out then that'd be great.

**Comment by akiva** [comment]
2011 lol

**Comment by ThePixelDeveloper** [comment]
😱 Kohana is going offline this year, so probably not a good idea to maintain this.
